In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import math
import numpy as np
import matplotlib.pyplot as plt
from slam.ukf import compute_sigma_points, recover_gaussian

In [3]:
def transform_linear(points):
    points[[0], :] = points[[0], :] + 1
    points[[1], :] = points[[1], :] + 2
    
    return points

In [4]:
sigma = np.eye(3) * 0.1
mu = np.matrix([0, 0, 3]).T

n = mu.shape[0]
alpha = 0.9
beta = 2
kappa = 1
lambd = alpha*alpha*(n+kappa)-n

print(mu)
print(sigma)
print(20*'=')

sigma_points, w_m, w_c = compute_sigma_points(mu, sigma, lambd, alpha, beta)
print(sigma_points)
print(w_m)
print(w_c)

transform_linear(sigma_points)

mu, sigma = recover_gaussian(sigma_points, w_m, w_c)
print(20*'=')
print(mu)
print(sigma)

[[0]
 [0]
 [3]]
[[0.1 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.1]]
[[ 0.          0.56920998  0.          0.         -0.56920998  0.
   0.        ]
 [ 0.          0.          0.56920998  0.          0.         -0.56920998
   0.        ]
 [ 3.          3.          3.          3.56920998  3.          3.
   2.43079002]]
[0.07407407 0.15432099 0.15432099 0.15432099 0.15432099 0.15432099
 0.15432099]
[2.26407407 0.15432099 0.15432099 0.15432099 0.15432099 0.15432099
 0.15432099]
[[1.]
 [2.]
 [3.]]
[[0.1 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.1]]
